spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true

logging:
  level:
    com.ley.springboot.mybatis.tk: debug
